### ISSUE TITLE
Uploading to splat.ink using -M while in the middle of a Salmon Run game crashes s3s

### ISSUE THREAD

**Issue by EtchJetty** [frozenpandaman/s3s#60] opened 2022-10-23 22:41 UTC
Pretty simple bug, and hopefully reproducible. I left s3s v0.1.6 running with ``python s3s.py -M -r`` and it crashed with this Traceback when it tried uploading my recent battles while I was in a Salmon Run game. 

```
Traceback (most recent call last):
  File "C:\Users\hjtfir\Development\silliness\scripting\s3s\s3s.py", line 1234, in <module>
    main()
  File "C:\Users\hjtfir\Development\silliness\scripting\s3s\s3s.py", line 1213, in main
    monitor_battles(which, secs, blackout, test_run)
  File "C:\Users\hjtfir\Development\silliness\scripting\s3s\s3s.py", line 988, in monitor_battles
    outcome = "Success" if result["job_result"]["is_clear"] == True else "Failure"
KeyError: 'job_result'
```

**Comment by frozenpandaman** [comment] 2022-10-24 00:45
Please update to the latest version. :)

Dupe of #57

**Closed** 2022-10-24 00:45 UTC
