### ISSUE TITLE
current rank not sent with -M

### ISSUE THREAD

**Issue by paul-sama** [frozenpandaman/s3s#46] opened 2022-10-09 01:58 UTC
https://github.com/fetus-hina/stat.ink/issues/1094

`-M` or `-r` didn't sent rank to stat.ink
`-o` then `-i` can show rank at battles page

**Comment by frozenpandaman** [comment] 2022-10-09 03:57
Thanks for the heads up, and to @Toufool too. I've been traveling and haven't had the time to play Splatoon recently, or do all that much testing while playing in monitoring mode.

This line
https://github.com/frozenpandaman/s3s/blob/c1f22a39a18caca0ecd9c7ed4931b5e9301c5712/s3s.py#L544
 _should_ trigger in `-M` mode (`-r` is another story, so maybe we'll have to change the logic here…), fetch the data in the following line that does the `BankaraBattleHistoriesQuery` GraphQL query and then send it if there's a match. Please let me know if you have more information, like if you know this `if` statement specifically isn't being triggered or something, and otherwise I'll look into this soon!

**Comment by frozenpandaman** [comment] 2022-10-09 10:02
This is now fixed with `-r` (verified with recent battles I uploaded: https://stat.ink/@frozenpandaman/spl3/8e2b1fb8-4ee8-4125-8dc7-8fb8352ca029)

@paul-sama Can you verify if it's fixed with `-M` now as well?

**Comment by paul-sama** [comment] 2022-10-09 10:25
still no rank with `-M`

**Comment by Toufool** [comment] 2022-10-18 14:58
When using -M, with one battle being found (latest battle) i did some debugging and found it was never meeting the condition below. Battle id never equaled child id, so ranks were never being set. So it may have to do with the difference in the battle that is passed in between -m and -r?

https://github.com/frozenpandaman/s3s/blob/c1f22a39a18caca0ecd9c7ed4931b5e9301c5712/s3s.py#L561

**Comment by frozenpandaman** [comment] 2022-10-19 09:32
@Toufool Thanks! I've been decently busy lately and have not had a ton of time for this project, but that's helpful + good to know, and I'll try to work toward fixing this soon. I think that _should_ be triggered, though, hmm… that's how it's able to match up the same battle between the two JSONs/requests and get the rank info!

**Comment by Toufool** [comment] 2022-10-20 04:26
still looking into this but its something with fetch_json

-r is calling 

splatnet_ids = fetch_json(which, specific=True, numbers_only=True)

-M is calling

ink_results, salmon_results = fetch_json(which, separate=True, numbers_only=True)

when i dump splanet_ids and ink_results, the ids are different.

**Comment by Toufool** [comment] 2022-10-21 03:28
fixed this

https://github.com/frozenpandaman/s3s/pull/54/commits/9c9731dfb163b82958dbb580564d02c7960ecf47

It looks like the different queries give different id's, so i had to match what the fetch_json's were doing in -r vs. -M.  Confirmed it sent the info over https://stat.ink/@Toufool/spl3/69f781b7-25a1-4909-bfd1-bc233e173a1e

**Comment by frozenpandaman** [comment] 2022-11-18 09:57
Finally had time to look into this and OHHH, this is why it's getting messed up!!!
The recent battle ID `-M` is fetching begins with `VsHistoryDetail-u-yourplayercode:RECENT:`, but the Ranked overview screen it's comparing it to begins with `VsHistoryDetail-u-yourplayercode:BANKARA:` (for the same battle!) so it'll never match, and the [condition](https://github.com/frozenpandaman/s3s/blob/4a9de614b11d54dd5e9880f870b23224688b285f/s3s.py#L644) will never trigger.

I'll decode this, change the string, then re-encode it, which should trick the battle IDs into being the same. So I'll fix this shortly! :)

**Closed** 2022-11-18 11:19 UTC
